# Generated by Django 5.2 on 2025-05-02 08:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientsOdoo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=255, unique=True)),
                ('client_odoo_url', models.TextField()),
                ('client_odoo_db', models.CharField(max_length=255)),
                ('client_odoo_api_user', models.CharField(max_length=255)),
                ('client_odoo_encrypted_api_key', models.TextField()),
            ],
            options={
                'verbose_name': 'Client Odoo',
                'verbose_name_plural': 'Clients Odoo',
            },
        ),
        migrations.CreateModel(
            name='ConfigurationCabinet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firm_odoo_url', models.TextField()),
                ('firm_odoo_db', models.CharField(max_length=255)),
                ('firm_odoo_api_user', models.CharField(max_length=255)),
                ('firm_odoo_encrypted_api_key', models.TextField()),
            ],
            options={
                'verbose_name': 'Configuration Cabinet',
                'verbose_name_plural': 'Configuration Cabinet',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('collaborateur', 'Collaborateur')], max_length=20)),
                ('odoo_collaborator_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Utilisateur',
                'verbose_name_plural': 'Profils Utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='IndicateursHistoriques',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('indicator_name', models.CharField(max_length=255)),
                ('indicator_value', models.TextField(blank=True, null=True)),
                ('extraction_timestamp', models.DateTimeField()),
                ('assigned_odoo_collaborator_id', models.CharField(blank=True, max_length=255, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clientsodoo')),
            ],
            options={
                'verbose_name': 'Indicateur Historique',
                'verbose_name_plural': 'Indicateurs Historiques',
                'ordering': ['-extraction_timestamp'],
                'indexes': [models.Index(fields=['client', '-extraction_timestamp'], name='core_indica_client__6a604f_idx'), models.Index(fields=['assigned_odoo_collaborator_id'], name='core_indica_assigne_3b8a98_idx')],
            },
        ),
    ]
