# Generated by Django 5.2 on 2025-05-02 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientsodoo',
            options={'ordering': ['client_name'], 'verbose_name': 'Client Odoo', 'verbose_name_plural': 'Clients Odoo'},
        ),
        migrations.AlterModelOptions(
            name='configurationcabinet',
            options={'verbose_name': 'Configuration Odoo Cabinet', 'verbose_name_plural': 'Configuration Odoo Cabinet'},
        ),
        migrations.AlterModelOptions(
            name='indicateurshistoriques',
            options={'ordering': ['-extraction_timestamp', 'client__client_name', 'indicator_name'], 'verbose_name': 'Indicateur Historique', 'verbose_name_plural': 'Indicateurs Historiques'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Profil Utilisateur OdooDash', 'verbose_name_plural': 'Profils Utilisateurs OdooDash'},
        ),
        migrations.AddField(
            model_name='indicateurshistoriques',
            name='assigned_collaborator_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom Collaborateur Assigné (Odoo Cabinet)'),
        ),
        migrations.AlterField(
            model_name='clientsodoo',
            name='client_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nom du Client'),
        ),
        migrations.AlterField(
            model_name='clientsodoo',
            name='client_odoo_api_user',
            field=models.CharField(max_length=255, verbose_name='Utilisateur API Odoo Client'),
        ),
        migrations.AlterField(
            model_name='clientsodoo',
            name='client_odoo_db',
            field=models.CharField(max_length=255, verbose_name='Nom BDD Odoo Client'),
        ),
        migrations.AlterField(
            model_name='clientsodoo',
            name='client_odoo_encrypted_api_key',
            field=models.TextField(verbose_name='Clé API Odoo Client (Chiffrée)'),
        ),
        migrations.AlterField(
            model_name='clientsodoo',
            name='client_odoo_url',
            field=models.TextField(verbose_name='URL Odoo Client (depuis Cabinet)'),
        ),
        migrations.AlterField(
            model_name='configurationcabinet',
            name='firm_odoo_api_user',
            field=models.CharField(max_length=255, verbose_name='Utilisateur API Odoo Cabinet'),
        ),
        migrations.AlterField(
            model_name='configurationcabinet',
            name='firm_odoo_db',
            field=models.CharField(max_length=255, verbose_name='Nom BDD Odoo Cabinet'),
        ),
        migrations.AlterField(
            model_name='configurationcabinet',
            name='firm_odoo_encrypted_api_key',
            field=models.TextField(verbose_name='Clé API Odoo Cabinet (Chiffrée)'),
        ),
        migrations.AlterField(
            model_name='configurationcabinet',
            name='firm_odoo_url',
            field=models.TextField(verbose_name='URL Odoo Cabinet'),
        ),
        migrations.AlterField(
            model_name='indicateurshistoriques',
            name='assigned_odoo_collaborator_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID Partenaire Collaborateur (Odoo Cabinet)'),
        ),
        migrations.AlterField(
            model_name='indicateurshistoriques',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clientsodoo', verbose_name='Client Odoo Concerné'),
        ),
        migrations.AlterField(
            model_name='indicateurshistoriques',
            name='extraction_timestamp',
            field=models.DateTimeField(verbose_name='Date/Heure Extraction'),
        ),
        migrations.AlterField(
            model_name='indicateurshistoriques',
            name='indicator_name',
            field=models.CharField(max_length=255, verbose_name='Nom Indicateur'),
        ),
        migrations.AlterField(
            model_name='indicateurshistoriques',
            name='indicator_value',
            field=models.TextField(blank=True, null=True, verbose_name='Valeur Indicateur'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='odoo_collaborator_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID Partenaire Odoo du Collaborateur'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('collaborateur', 'Collaborateur')], max_length=20, verbose_name='Rôle dans OdooDash'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur Django lié'),
        ),
        migrations.AddIndex(
            model_name='indicateurshistoriques',
            index=models.Index(fields=['indicator_name'], name='core_indica_indicat_c4a99d_idx'),
        ),
    ]
