# Generated by Django 5.2.1 on 2025-05-13 06:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_clientsodoo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOdooStatus',
            fields=[
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.clientsodoo', verbose_name='Client Odoo Associé')),
                ('last_connection_attempt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Dernière Tentative de Connexion')),
                ('connection_successful', models.BooleanField(default=False, verbose_name='Connexion Réussie')),
                ('last_error_message', models.TextField(blank=True, null=True, verbose_name="Dernier Message d'Erreur")),
            ],
            options={
                'verbose_name': 'Statut Connexion Client Odoo',
                'verbose_name_plural': 'Statuts Connexion Clients Odoo',
                'ordering': ['-last_connection_attempt'],
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
